app/assets/hr-assist-front-end/client/js/custom/_common/services/autocomplete.service.js
app/assets/hr-assist-front-end/client/js/custom/components/employee/controllers/employeeEquipments.controller.js
app/assets/hr-assist-front-end/client/js/custom/components/employee/controllers/employeeHoliday.controller.js
app/assets/hr-assist-front-end/client/js/custom/components/employee/controllers/employeeJobs.controller.js
app/assets/hr-assist-front-end/client/js/custom/components/employee/controllers/employeeProjects.controller.js
app/assets/hr-assist-front-end/client/js/custom/components/employee/controllers/employeeSchedule.controller.js
app/assets/hr-assist-front-end/client/js/custom/components/employee/controllers/employeeSkills.controller.js
app/assets/hr-assist-front-end/client/js/custom/components/employee/models/employee.model.js
app/assets/hr-assist-front-end/client/js/custom/components/employee/views/employeeGeneralInfo.view.html
app/assets/hr-assist-front-end/client/js/custom/components/employee/views/employees.view.html

Task #16323 - Update routes for employees

Task #16323 - Update routes for employees

---

app/assets/hr-assist-front-end/client/js/custom/components/extra/controllers/extraForm.controller.js
app/assets/hr-assist-front-end/client/js/custom/components/extra/controllers/extraList.controller.js
app/assets/hr-assist-front-end/client/js/custom/components/extra/views/extraForm.view.html
app/assets/hr-assist-front-end/client/js/custom/components/extra/views/extraList.industries.view.html

This pull request is for industry route & industry CRUD

Task 16329

---

app/assets/front-end/src/javascript/components/employee/holidays/userHoliday.controller.js
app/assets/front-end/src/javascript/components/employee/holidays/userHoliday.view.html

Bug #16596 Employee Holidays start/end date validate

---

app/assets/front-end/bower.json
app/assets/front-end/config.yml
app/assets/front-end/src/javascript/components/employee/details/userDetails.view.html
app/assets/front-end/src/javascript/components/employee/education/userEducation.view.html
app/assets/front-end/src/javascript/components/employee/general/userGeneral.controller.js
app/assets/front-end/src/javascript/components/employee/general/userGeneral.view.html
app/assets/front-end/src/javascript/components/employee/languages/userLanguages.view.html
app/assets/front-end/src/javascript/components/employee/projects/employeeProjects.view.html
app/assets/front-end/src/javascript/main.module.js

Fix generate cv and profile picture

fix cv generate and change profile picture mode

---

app/assets/front-end/src/javascript/common/autocomplete/autocomplete.service.js
app/assets/front-end/src/javascript/components/employee/devices/userDevices.controller.js
app/assets/front-end/src/javascript/components/employee/devices/userDevices.view.html
app/assets/front-end/src/javascript/components/employee/general/userGeneral.controller.js
app/assets/front-end/src/javascript/components/employee/general/userGeneral.view.html
app/assets/front-end/src/javascript/components/employee/languages/userLanguages.controller.js
app/assets/front-end/src/javascript/components/employee/languages/userLanguages.view.html

Employee -> General Information validation rulles,
Language list on focus,
Device list on focus

Task #16739 

---

app/assets/front-end/src/javascript/components/employee/devices/userDevices.controller.js
app/assets/front-end/src/javascript/components/employee/devices/userDevices.view.html
app/assets/front-end/src/javascript/components/employee/education/userEducation.controller.js
app/assets/front-end/src/javascript/components/employee/education/userEducation.view.html
app/assets/front-end/src/javascript/components/employee/holidays/userHoliday.view.html
app/assets/front-end/src/javascript/components/employee/languages/userLanguages.controller.js
app/assets/front-end/src/javascript/components/employee/languages/userLanguages.view.html

Fix save with custom data in autocomplete input

Bug #16726

---

app/assets/front-end/src/javascript/common/services/formatDate.service.js
app/assets/front-end/src/javascript/components/employee/general/userGeneral.controller.js
app/assets/front-end/src/javascript/components/employee/general/userGeneral.view.html
app/assets/front-end/src/javascript/components/employee/holidays/userHoliday.controller.js

remove office email and schedule type

General info

---

app/assets/front-end/src/javascript/components/employee/education/userEducation.controller.js

fix "Data de incepere si finalizare se salveaza cu o zi mai putin".

Task-#16850 fix Education start/end date

---

app/assets/front-end/src/javascript/components/project/details/projectDetails.view.html
app/assets/front-end/src/javascript/components/project/industries/projectIndustries.controller.js
app/assets/front-end/src/javascript/components/project/industries/projectIndustries.directive.js
app/assets/front-end/src/javascript/components/project/industries/projectIndustries.view.html

Add Notes.
implement validation.
fix saving change.
dropdown bottom orientation, lose dropdown focus after add item.

Task #16859 Projects Add/Edit Industries fix

---

app/assets/front-end/src/javascript/components/project/customers/projectCustomers.controller.js
app/assets/front-end/src/javascript/components/project/customers/projectCustomers.directive.js
app/assets/front-end/src/javascript/components/project/customers/projectCustomers.view.html
app/assets/front-end/src/javascript/components/project/details/projectDetails.view.html

Add Notes.
Implement validation.
Fix saving change.
Dropdown bottom orientation, lose dropdown focus after add item.

Task #16860 Projects Add/Edit Customers fixes

---

app/assets/front-end/src/javascript/components/project/appType/projectAppTypes.controller.js
app/assets/front-end/src/javascript/components/project/appType/projectAppTypes.directive.js
app/assets/front-end/src/javascript/components/project/appType/projectAppTypes.view.html
app/assets/front-end/src/javascript/components/project/details/projectDetails.view.html
app/assets/front-end/src/javascript/components/project/employees/projectEmployees.controller.js
app/assets/front-end/src/javascript/components/project/employees/projectEmployees.directive.js
app/assets/front-end/src/javascript/components/project/employees/projectEmployees.view.html
app/assets/front-end/src/javascript/components/project/general/projectGeneral.controller.js
app/assets/front-end/src/javascript/components/project/general/projectGeneral.directive.js
app/assets/front-end/src/javascript/components/project/general/projectGeneral.view.html

Add Notes.
Refactor validation.

Task #16861 Projects Add/Edit Application Types, Employees, General Inforamtions

---

app/assets/front-end/src/javascript/components/employee/details/userDetails.view.html
app/assets/front-end/src/javascript/components/employee/general/userGeneral.view.html
app/assets/front-end/src/javascript/components/employee/holidays/userHoliday.controller.js
app/assets/front-end/src/javascript/components/employee/holidays/userHoliday.directive.js
app/assets/front-end/src/javascript/components/employee/holidays/userHoliday.view.html
app/assets/front-end/src/sass/base/_2_general.sass

md-require-match & required was removed from autocomplete projects, and employee, more details in html commented code.

Task #16884 Add delete btn for extra project, replacement fields

---

app/assets/front-end/src/javascript/components/project/projects/projects.controller.js
app/assets/front-end/src/javascript/components/project/projects/projects.view.html

Task #16886 fixed Projects Export CSV

---

app/assets/front-end/src/javascript/components/project/projects/projects.controller.js
app/assets/front-end/src/javascript/components/project/projects/projects.view.html

Fixed default sorting page bug when moving between tables.

Fixed order bug and wrong pagination when multiple search

---

app/assets/front-end/src/javascript/components/employee/details/userDetails.view.html
app/assets/front-end/src/javascript/components/employee/education/userEducation.controller.js
app/assets/front-end/src/javascript/components/employee/education/userEducation.directive.js
app/assets/front-end/src/javascript/components/employee/education/userEducation.view.html

Before deleting a diploma, should appear a message "are you sure ..."
Refactor code

Task #16896

---

app/assets/front-end/src/javascript/components/employee/general/userGeneral.controller.js
app/assets/front-end/src/javascript/components/employee/general/userGeneral.view.html
app/assets/front-end/src/javascript/components/employee/models/user.model.js
app/assets/front-end/src/javascript/components/employee/users/users.view.html

Implemented  functionality of Europass CV, need more back-end and front end support to complete all the fields.
Cross-origin resource sharing need to be enable for https://europass.cedefop.europa.eu/rest/v1/document/to/pdf-cv

Implement Europass CV

---

app/assets/front-end/src/javascript/components/project/form/projectForm.view.html
app/assets/front-end/src/javascript/components/project/general/projectGeneral.controller.js
app/assets/front-end/src/javascript/components/project/general/projectGeneral.view.html

Remove required description when add project, disable date validate on general info project.

Fix projects Remove required description when add project, disable date validate on general info project

---

app/assets/front-end/src/javascript/components/employee/courses/employeeCourses.controller.js
app/assets/front-end/src/javascript/components/employee/courses/employeeCourses.directive.js
app/assets/front-end/src/javascript/components/employee/courses/employeeCourses.view.html
app/assets/front-end/src/javascript/components/employee/details/userDetails.controller.js
app/assets/front-end/src/javascript/components/employee/details/userDetails.view.html
app/assets/front-end/src/javascript/components/employee/models/user.model.js

Courses and certifications card

Task #16955 -> Courses and certifications

---

app/assets/front-end/src/javascript/components/employee/users/users.controller.js

fix generate excel after reset filter

Task-#17077 fix generate excel after reset filter

---

app/assets/front-end/src/javascript/components/employee/filters/usersFilters.view.html
app/assets/front-end/src/javascript/components/employee/users/users.controller.js

fix filter just by birthday month and refactor few line of code

Task-#17077 fix filter just by birthday month

---

app/assets/front-end/src/javascript/components/employee/general/userGeneral.controller.js

Reverts assist-software/hr-assist#245

Revert "Bug #16962"

---

app/assets/front-end/src/javascript/common/autocomplete/autocomplete.service.js
app/assets/front-end/src/javascript/components/employee/general/userGeneral.controller.js
app/assets/front-end/src/javascript/components/employee/general/userGeneral.view.html
app/assets/front-end/src/javascript/components/employee/holidays/userHoliday.controller.js
app/assets/front-end/src/javascript/components/holiday/directives/holidays.directive.js
app/assets/front-end/src/javascript/components/holiday/form/holidayForm.controller.js

fixed CV, implement generate doc cv, fixed autocomplete bug

Bug-#16962 fixed CV, implement generate doc cv, fixed autocomplete bug

---

app/api/api_helpers.rb

Reverts assist-software/hr-assist#252

Revert "[Task-17138] Added level in languages object when users?with[]=langua…"

---

app/assets/front-end/src/javascript/components/employee/filters/usersFilters.view.html
app/assets/front-end/src/javascript/components/employee/models/user.model.js
app/assets/front-end/src/javascript/components/employee/users/users.controller.js
app/assets/front-end/src/javascript/components/employee/users/users.view.html
app/assets/front-end/src/sass/components/_filters.sass

Added language and technology level, certification and courses in exported excel file, also added in view table.

Task #17077

---

app/assets/front-end/bower.json
app/assets/front-end/config.yml
app/assets/front-end/src/javascript/components/employee/general/userGeneral.controller.js
app/assets/front-end/src/javascript/components/employee/general/userGeneral.view.html
app/assets/front-end/src/javascript/components/employee/models/user.model.js
app/assets/front-end/src/javascript/main.module.js

- Add in cv languages with level
- Separate model from controller
- Refactor few functions
- Remove MD5 algorithm from controller and add new Angular module "angular-md5"
- Remove unnecessary comments
- Resize CV image for better fit

Bug #16962 Add in cv language level

---

app/assets/front-end/src/javascript/components/employee/holidays/userHoliday.controller.js
app/assets/front-end/src/javascript/components/employee/holidays/userHoliday.view.html
app/assets/front-end/src/javascript/components/holiday/views/holidayParent.view.html
app/assets/front-end/src/javascript/main.routes.js

remove on Employee Holidays, team leader autocomplete focus bug

Feature-#16942 fixed holiday route bug

---

app/assets/front-end/src/javascript/components/employee/general/userGeneral.view.html

Added on general info card  SSH public key, bitbucket and github Username field

Feature #17115

---

app/assets/front-end/src/javascript/components/candidates/candidates/candidates.controller.js
app/assets/front-end/src/javascript/components/candidates/candidates/candidates.directive.js
app/assets/front-end/src/javascript/components/candidates/candidates/candidates.view.html
app/assets/front-end/src/javascript/components/candidates/filters/candidatesFilters.directive.js
app/assets/front-end/src/javascript/components/candidates/filters/candidatesFilters.view.html
app/assets/front-end/src/javascript/components/candidates/form/candidateForm.controller.js
app/assets/front-end/src/javascript/components/candidates/form/candidateForm.view.html
app/assets/front-end/src/javascript/components/candidates/models/candidates.model.js
app/assets/front-end/src/javascript/components/candidates/upload/uploadFiles.controller.js
app/assets/front-end/src/javascript/components/candidates/upload/uploadFiles.directive.js
app/assets/front-end/src/javascript/components/candidates/upload/uploadFiles.view.html
app/assets/front-end/src/javascript/components/employee/users/users.controller.js
app/assets/front-end/src/javascript/main.routes.js
app/assets/front-end/src/pages/index.html
app/assets/front-end/src/sass/components/_holiday.sass

Task #16998

---

app/assets/front-end/src/javascript/components/employee/models/user.model.js
app/assets/front-end/src/javascript/components/employee/technologies/employeeTechnologies.controller.js
app/assets/front-end/src/javascript/components/employee/technologies/employeeTechnologies.view.html

- get rid of $scope, $timeout, $stateParams services;
- implement adding multiple tehnologies;
- change update technologies mode;

fix user technologies

---

app/assets/front-end/src/javascript/components/employee/details/userDetails.view.html
app/assets/front-end/src/javascript/components/employee/devices/userDevices.controller.js
app/assets/front-end/src/javascript/components/employee/devices/userDevices.directive.js
app/assets/front-end/src/javascript/components/employee/devices/userDevices.view.html
app/assets/front-end/src/javascript/components/employee/education/userEducation.view.html
app/assets/front-end/src/javascript/components/employee/general/userGeneral.controller.js
app/assets/front-end/src/javascript/components/employee/general/userGeneral.view.html
app/assets/front-end/src/javascript/components/employee/holidays/userHoliday.controller.js
app/assets/front-end/src/javascript/components/employee/holidays/userHoliday.view.html
app/assets/front-end/src/javascript/components/employee/languages/userLanguages.controller.js
app/assets/front-end/src/javascript/components/employee/languages/userLanguages.view.html
app/assets/front-end/src/javascript/components/employee/projects/employeeProjects.controller.js
app/assets/front-end/src/javascript/components/employee/projects/employeeProjects.directive.js
app/assets/front-end/src/javascript/components/employee/projects/employeeProjects.view.html
app/assets/front-end/src/sass/base/_2_general.sass
app/assets/front-end/src/sass/components/_employee-profile.sass
app/assets/front-end/src/sass/components/_inputs.sass
app/assets/front-end/src/sass/components/_table.sass

Bugs fixing-> https://docs.google.com/spreadsheets/d/1ZKqWAN8NBuINZrQ7GGc_TIkvd14ocqkg7ThAtnSKvYI/edit#gid=364777918

Bug fixing

---

app/assets/front-end/src/javascript/components/employee/courses/employeeCourses.controller.js
app/assets/front-end/src/javascript/components/employee/education/userEducation.controller.js
app/assets/front-end/src/javascript/components/employee/general/userGeneral.controller.js
app/assets/front-end/src/javascript/components/employee/holidays/userHoliday.view.html
app/assets/front-end/src/javascript/components/employee/languages/userLanguages.controller.js
app/assets/front-end/src/javascript/components/employee/models/user.model.js
app/assets/front-end/src/javascript/components/employee/projects/employeeProjects.controller.js
app/assets/front-end/src/javascript/components/employee/projects/employeeProjects.view.html
app/assets/front-end/src/javascript/components/employee/technologies/employeeTechnologies.controller.js
app/assets/front-end/src/javascript/components/employee/technologies/employeeTechnologies.view.html
app/assets/front-end/src/sass/components/_table.sass

fix remained bugs, and new ones
https://docs.google.com/spreadsheets/d/1ZKqWAN8NBuINZrQ7GGc_TIkvd14ocqkg7ThAtnSKvYI/edit#gid=364777918

fixes at user cv, holidays, project, languages

---

app/assets/front-end/src/javascript/components/employee/holidays/userHoliday.controller.js
app/assets/front-end/src/javascript/components/employee/holidays/userHoliday.view.html

Bug-#16960 team leader required field

---

app/assets/front-end/src/javascript/components/holiday/details/holidayDetails.view.html
app/assets/front-end/src/javascript/components/holiday/form/holidayForm.view.html
app/assets/front-end/src/javascript/components/holiday/holidays/holidays.controller.js
app/assets/front-end/src/javascript/components/holiday/holidays/holidays.view.html
app/assets/front-end/src/javascript/components/holiday/models/holiday.model.js

Task #17104 added remove functionality in Holidays tab,
fix holiday preview

Task-#17104 added remove functionality in Holidays tab

---

app/assets/front-end/src/javascript/components/employee/languages/userLanguages.controller.js
app/assets/front-end/src/javascript/components/employee/languages/userLanguages.view.html

fixed languages bugs from Bugs doc

fixed languages bugs

---

app/assets/front-end/bower.json

Update material angularjs to v1.1.5, fix for:  https://github.com/assist-software/hr-assist/issues/321

update material angularjs to fix #321 issues

---

app/assets/front-end/src/javascript/components/employee/technologies/employeeTechnologies.controller.js

- Enable save after delete a technology

[Task-#19273] - Fix technology save btn bug

---

app/assets/front-end/src/javascript/components/employee/courses/employeeCourses.controller.js
app/assets/front-end/src/javascript/components/employee/courses/employeeCourses.view.html
app/assets/front-end/src/javascript/components/employee/models/user.model.js

- Add max date at Courses section
- Fix delete device, language, education, project, certifications, holiday Employee section related

[Task #19302] - Fix some employee related bugs

---

app/assets/front-end/src/javascript/components/login/directives/login.directive.js
app/assets/front-end/src/javascript/components/login/services/userFactory.service.js
app/assets/front-end/src/javascript/components/login/views/login.form.view.html
app/assets/front-end/src/sass/base/_2_general.sass
app/assets/front-end/src/sass/components/_login.sass

- Please add error message at login, and remove all errors for debugging from app.

[Task-#19506] - Add error message at login page
